# Apply this document and `kubectl edit` the records to see hashes and serials update.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
    - zones: ["*.example.org."]
    - records:
      - pattern: "*.subdomain.example.org."
      - pattern: "www.example.org."
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-ref-example-org
spec:
  domainName: www.ref.example.org.
  type: A
  rdata: "192.168.0.1"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-example-org
spec:
  domainName: www.example.org.
  type: A
  rdata: "192.168.0.2"
---
apiVersion: kubi.zone/v1alpha1
kind: ZoneFile
metadata:
  name: example
spec:
  zoneRefs:
    - name: example-org
    - name: subdomain-example-org
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www2-example-org
spec:
  domainName: www2.example.org.
  type: CNAME
  rdata: "www.example.org."
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: subdomain-example-org
spec:
  domainName: subdomain
  zoneRef:
    name: example-org
  delegations:
    - zones: ["www.subdomain.example.org."]
    - records:
        - pattern: "ns*.subdomain.example.org."
          types: ["A"]
        - pattern: "subdomain.example.org."
          types: ["NS"]
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-subdomain-example-org
spec:
  domainName: www.subdomain.example.org.
  type: A
  rdata: "192.168.0.2"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns1-subdomain-example-org
spec:
  domainName: ns1.subdomain.example.org.
  type: A
  rdata: "192.168.0.10"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns2-subdomain-example-org
spec:
  domainName: ns2.subdomain.example.org.
  type: A
  rdata: "192.168.0.11"
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns-ns1-subdomain-example-org
spec:
  domainName: subdomain.example.org.
  type: NS
  rdata: ns1.subdomain.example.org.
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: ns-ns2-subdomain-example-org
spec:
  domainName: subdomain.example.org.
  type: NS
  rdata: ns2.subdomain.example.org.